### ISSUE TITLE
'Figure & Code' tab: the code section overlaps the figure

### ISSUE THREAD

**Issue by daattali** [jennybc/r-graph-catalog#11]
This only happens in the stats Shiny server, but not locally

**Comment by jennybc** [comment]
It looks correct for me locally, so check this against the stat shiny server:

```
Session info ------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.878)          
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       America/Vancouver           
 date     2016-02-17                  

Packages ----------------------------------------------------------------------------
 package   * version date       source        
 digest      0.6.9   2016-01-08 CRAN (R 3.2.3)
 htmltools   0.3     2015-12-29 CRAN (R 3.2.3)
 httpuv      1.3.3   2015-08-04 CRAN (R 3.2.0)
 jsonlite    0.9.19  2015-11-28 CRAN (R 3.2.2)
 mime        0.4     2015-09-03 CRAN (R 3.2.0)
 R6          2.1.2   2016-01-26 CRAN (R 3.2.3)
 Rcpp        0.12.3  2016-01-10 CRAN (R 3.2.3)
 shiny     * 0.13.0  2016-01-12 CRAN (R 3.2.3)
 xtable      1.8-0   2015-11-02 CRAN (R 3.2.0)
```

**Comment by daattali** [comment]
It seems that the server app is running the same version of shiny and bootrstrap and jquery (I didn't have to log into the server machine to view this, if you just view the source of the HTML , Shiny prints out the versions of various libraries).

So, it's not that....

**Comment by daattali** [comment]
Ah huh!  This problem was actually fixed by Joanna over a year ago, but it seems that the stats server is not running the updated CSS file

https://github.com/jennybc/r-graph-catalog/commit/ec85e1aba6fd7e87033c0d64770920f8f4a7d069#diff-1d808f785f3d695cb1f722e2ef0c6232

**Comment by jennybc** [comment]
I've remade all the figures and pushed all the changes from Joanna, you, and me to the server. And I can see many (often subtle) changes. But once you click on a figure to get to the figure vs code view? The figure aspect ratio is still wrong. Do you have any more ideas about that?

**Comment by daattali** [comment]
Seems like that commit from a year ago only dealt with restricting the width.

I just pushed a commit that I believe fixes aspect ratio for all images

**Comment by jennybc** [comment]
OK your fixed worked for 'figure and code' view (https://github.com/jennybc/r-graph-catalog/commit/143b4740461ec7d3cb302d2b9896186e53d7c4d5). But aspect ratio was still wrong for the 'figure only'. But I have now fixed that as well (https://github.com/jennybc/r-graph-catalog/commit/cc77359df6c6a1ab556da3d87a8687014f0d9bd0).
